# Generated by Django 4.0.3 on 2022-04-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='type_id',
            field=models.ForeignKey(default='radio-button', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.quiztype'),
        ),
    ]
