# Generated by Django 4.0.3 on 2022-05-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quizquestion_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestion'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
    ]
