# Generated by Django 4.0.3 on 2022-05-30 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_take_status_remove_takeanswer_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='percent_efficiency',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='take',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='take',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
        migrations.AlterField(
            model_name='take',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='takeanswer',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizanswer'),
        ),
        migrations.AlterField(
            model_name='takeanswer',
            name='take_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.take'),
        ),
    ]
